pyTorch 여러 함수들

In [3]:
import torch
A = torch.randn(3,3) # normal distribution
B = torch.rand(3,3) # uniform distribution
print(A)
print(B)

tensor([[ 0.5265, -0.2659,  1.3731],
        [-0.4457,  2.0278, -1.6592],
        [ 0.2624, -1.3237, -0.5741]])
tensor([[0.9215, 0.1754, 0.9613],
        [0.6686, 0.9426, 0.7649],
        [0.0598, 0.3502, 0.2214]])


In [ ]:
A = torch.randn(3,3)
print(A)
print(torch.abs(A)) # 절댓값 |x|
print(torch.sqrt(torch.abs(A))) # 제곱근(루트) \sqrt{x}
print(torch.exp(A)) # 자연상수 지수 e^x
print(torch.log(torch.abs(A))) # 자연로그 ln(x)
print(torch.log(torch.exp(torch.tensor(1)))) # ln(e^1) = 1 확인
print(torch.log10(torch.tensor(10))) # 상용로그 log_10(x)
print(torch.log2(torch.tensor(2))) # 이진로그 log_2(x)
print(torch.round(A)) # 반올림 (정수)
print(torch.round(A,decimals=2)) # 소수점 둘째 자리까지 반올림
print(torch.floor(A)) # 내림 (바닥 함수)
print(torch.ceil(A)) # 올림 (천장 함수)

tensor([[-1.6092,  0.9007,  0.1025],
        [-0.8948, -0.2021,  0.7984],
        [-1.2676, -0.2743,  1.1282]])
tensor([[1.6092, 0.9007, 0.1025],
        [0.8948, 0.2021, 0.7984],
        [1.2676, 0.2743, 1.1282]])
tensor([[1.2686, 0.9490, 0.3201],
        [0.9459, 0.4496, 0.8935],
        [1.1259, 0.5238, 1.0622]])
tensor([[0.2000, 2.4613, 1.1079],
        [0.4087, 0.8170, 2.2219],
        [0.2815, 0.7601, 3.0901]])
tensor([[ 0.4758, -0.1046, -2.2784],
        [-0.1112, -1.5990, -0.2252],
        [ 0.2371, -1.2934,  0.1206]])
tensor(1.)
tensor(1.)
tensor(1.)
tensor([[-2.,  1.,  0.],
        [-1., -0.,  1.],
        [-1., -0.,  1.]])
tensor([[-1.6100,  0.9000,  0.1000],
        [-0.8900, -0.2000,  0.8000],
        [-1.2700, -0.2700,  1.1300]])
tensor([[-2.,  0.,  0.],
        [-1., -1.,  0.],
        [-2., -1.,  1.]])
tensor([[-1.,  1.,  1.],
        [-0., -0.,  1.],
        [-1., -0.,  2.]])


In [ ]:
print(torch.sin(torch.tensor(torch.pi/6))) # type(torch.pi)는 float지만 tensor와 연산시 tensor로 변함
print(torch.cos(torch.tensor(torch.pi/3)))
print(torch.tan(torch.tensor(torch.pi/4)))
print(torch.tanh(torch.tensor(-10)))

type(torch.tensor(1)/6) # 텐서랑 섞이면 뭐든 다 텐서

tensor(0.5000)
tensor(0.5000)
tensor(1.)
tensor(-1.)


torch.Tensor

In [ ]:
nan = torch.nan
inf = torch.inf
print(torch.log(torch.tensor(-1))) # log 음수는 정의 불가 -> nan 발생
print(torch.isnan(torch.tensor([1,2,nan,3,4]))) # nan(결측치) 여부 확인
print(torch.isinf(torch.tensor([1,2,3,4,inf]))) # inf(무한대) 여부 확인

tensor(nan)
tensor([False, False,  True, False, False])
tensor([False, False, False, False,  True])


In [ ]:
A = torch.randn(3,4)
print(A)
print(torch.max(A))
# 💡 핵심 원칙: "dim은 진행 방향이다!"
print(torch.max(A,dim=0)) # 각 '열'의 최댓값 (위아래로 꾹 누르기)
print(torch.max(A,dim=1)) # 각 '행'의 최댓값 (양옆에서 꾹 누르기)
print(torch.max(A,dim=0, keepdims=True)) # 차원 유지 (결과가 [1, 4] 모양이 됨)
print(torch.max(A,dim=1, keepdims=True)) # 차원 유지 (결과가 [3, 1] 모양이 됨)
print(torch.min(A))
print(torch.min(A,dim=0)) # 각 '열'의 최솟값
print(torch.min(A,dim=1)) # 각 '행'의 최솟값
print(torch.argmax(A))

print(torch.argmax(A,dim=0)) # 각 열에서 가장 큰 값의 인덱스
print(torch.argmax(A,dim=1)) # 각 행에서 가장 큰 값의 인덱스

tensor([[-0.3617, -0.0581,  0.6533, -0.7335],
        [ 0.8627, -1.9174,  0.0133,  1.8825],
        [ 0.9151, -0.6039,  0.9755, -0.3245]])
tensor(1.8825)
torch.return_types.max(
values=tensor([ 0.9151, -0.0581,  0.9755,  1.8825]),
indices=tensor([2, 0, 2, 1]))
torch.return_types.max(
values=tensor([0.6533, 1.8825, 0.9755]),
indices=tensor([2, 3, 2]))
torch.return_types.max(
values=tensor([[ 0.9151, -0.0581,  0.9755,  1.8825]]),
indices=tensor([[2, 0, 2, 1]]))
torch.return_types.max(
values=tensor([[0.6533],
        [1.8825],
        [0.9755]]),
indices=tensor([[2],
        [3],
        [2]]))
tensor(-1.9174)
torch.return_types.min(
values=tensor([-0.3617, -1.9174,  0.0133, -0.7335]),
indices=tensor([0, 1, 1, 0]))
torch.return_types.min(
values=tensor([-0.7335, -1.9174, -0.6039]),
indices=tensor([3, 1, 1]))
tensor(7)
tensor([2, 0, 2, 1])
tensor([2, 3, 2])


In [ ]:
# 인스턴스 메소드나 torch 함수나 같음
a = torch.randn(6,1)
print(a)
a_sorted = torch.sort(a,dim=0)
print(a_sorted)

a = torch.randn(6,1)
print(a)
print(a.sort(dim=0)) # 오름차순 정렬
print(a.sort(dim=0, descending=True)) # 내림차순 정렬 (큰 수가 위로)

print(torch.max(a))
print(a.max())
print(torch.abs(a))
print(a.abs())

tensor([[0.3552],
        [1.3243],
        [0.8332],
        [0.6882],
        [0.8568],
        [0.5989]])
torch.return_types.sort(
values=tensor([[0.3552],
        [0.5989],
        [0.6882],
        [0.8332],
        [0.8568],
        [1.3243]]),
indices=tensor([[0],
        [5],
        [3],
        [2],
        [4],
        [1]]))
tensor([[ 1.5945],
        [ 0.7344],
        [-1.0974],
        [ 0.4732],
        [-0.1865],
        [-1.3488]])
torch.return_types.sort(
values=tensor([[-1.3488],
        [-1.0974],
        [-0.1865],
        [ 0.4732],
        [ 0.7344],
        [ 1.5945]]),
indices=tensor([[5],
        [2],
        [4],
        [3],
        [1],
        [0]]))
torch.return_types.sort(
values=tensor([[ 1.5945],
        [ 0.7344],
        [ 0.4732],
        [-0.1865],
        [-1.0974],
        [-1.3488]]),
indices=tensor([[0],
        [1],
        [3],
        [4],
        [2],
        [5]]))
tensor(1.5945)
tensor(1.5945)
tensor([[1.5945],
        [0.7344],
        

In [ ]:
A = torch.randint(1,5,size=(12,)) # 1부터 5미만 12개 정수 (1차원은 (N,)으로 표현)
print(A)
print(A.shape)

B = A.reshape(2,2,3) # ★원소 총 개수(12개)가 맞아야 가능!
C = A.reshape(2,6)
print(B)
print(B.ndim) # 차원의 수(Rank) 확인
print(C.ndim)

tensor([4, 2, 4, 3, 4, 4, 4, 1, 1, 2, 3, 4])
torch.Size([12])
tensor([[[4, 2, 4],
         [3, 4, 4]],

        [[4, 1, 1],
         [2, 3, 4]]])
3
2


In [ ]:
A = torch.arange(20,)
print(A)
print(A.reshape(4,5))
print(A.reshape(4,-1).shape) # 4개 행에 맞게 열을 자동으로 맞춰줌 -> 4
print(A.reshape(2,5,-1).shape) 
print(A.reshape(2,-1,5).shape)
print(A.reshape(1,-1).shape) # 2차원 행벡터
print(A.reshape(-1,1).shape) # 2차원 열벡터

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])
tensor([[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]])
torch.Size([4, 5])
torch.Size([2, 5, 2])
torch.Size([2, 2, 5])
torch.Size([1, 20])
torch.Size([20, 1])


In [ ]:
a = torch.tensor([1,2,3])
b = torch.tensor([2,2,1])
print(torch.sum(a*b)) # 내적 (성분별 곱 -> 합)

a = a.reshape(3,1)
b = b.reshape(3,1)
# 아래 4줄은 모두 같은 연산 (전치 후 행렬곱 = 내적)
print(a.transpose(1,0)@b) # 1번 축과 0번 축을 '맞교환' (Swap) -> 오직 2개만 가능
print(a.permute(1,0)@b) # 0번, 1번 축을 [1, 0] 순서로 '재배열' (Reorder) -> 전체 순서 지정
print(a.T@b) # 전치행렬
print(a.t()@b)

A = torch.randn(4,3,6)
# 목표: (4, 3, 6) -> (4, 6, 3)
print(A.transpose(2,1).shape) # 2번 축과 1번 축의 '자리를 바꿈' (Swap)
print(A.permute(0,2,1).shape) # 모든 축을 [0번, 2번, 1번] 순서로 '줄 세움' (Reorder)

tensor(9)
tensor([[9]])
tensor([[9]])
tensor([[9]])
tensor([[9]])
torch.Size([4, 6, 3])
torch.Size([4, 6, 3])


In [ ]:
# 인덱싱 : Rank 감소, 슬라이싱 : Rank 유지
x = torch.randn(2,3,4,5,6)
# 1. 뒤쪽 차원 싹 다 가져오기
print(x[1,2,:,:,:].shape) # 앞의 두 차원(0,1번)은 특정해서 사라짐
print(x[1,2,...].shape)   # ...이 남은 뒤쪽(:, :, :)을 자동으로 채워줌

# 2. 앞쪽 차원 싹 다 가져오기
print(x[:,:,:,:,3].shape) # 마지막 차원(4번)만 특정해서 사라짐
print(x[...,3].shape)     # ...이 앞쪽(:, :, :, :)을 자동으로 채워줌

# 3. 중간 차원 싹 다 가져오기 (이게 제일 편함!)
print(x[1,:,:,3,:].shape) # 0번과 3번 차원만 특정해서 사라짐
print(x[1,...,3,:].shape) # ...이 중간에 낀 차원들(:, :)을 알아서 채워줌

torch.Size([4, 5, 6])
torch.Size([4, 5, 6])
torch.Size([2, 3, 4, 5])
torch.Size([2, 3, 4, 5])
torch.Size([3, 4, 6])
torch.Size([3, 4, 6])


In [31]:
A = torch.ones(3,4)
B = torch.zeros(3,4)
# 1. 위아래로 붙이기 (Vertical, 행이 늘어남)
C = torch.vstack([A,B]) # vstack: Vertical(세로)로 쌓기
E = torch.cat([A,B], dim=0) # cat(dim=0): 0번 축(세로) 방향으로 연결 ★(3차원 이상에서 이걸 주로 씀)
print(f"=== 세로 합체 (vstack / dim=0) ===")
print(C)
print(E)
print(f"Shape: {C.shape}") # (3+3, 4) -> (6, 4)

# 2. 양옆으로 붙이기 (Horizontal, 열이 늘어남)
D = torch.hstack([A,B]) # hstack: Horizontal(가로)로 쌓기
F = torch.cat([A,B], dim=1) # cat(dim=1): 1번 축(가로) 방향으로 연결

print(f"\n=== 가로 합체 (hstack / dim=1) ===")
print(D)
print(F)
print(f"Shape: {D.shape}") # (3, 4+4) -> (3, 8)

=== 세로 합체 (vstack / dim=0) ===
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
Shape: torch.Size([6, 4])

=== 가로 합체 (hstack / dim=1) ===
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
tensor([[1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.],
        [1., 1., 1., 1., 0., 0., 0., 0.]])
Shape: torch.Size([3, 8])


In [37]:
A = torch.randn(1,1,1,3,1,1,1,4,1,1,1) # 실제 데이터는 3과 4뿐이고 나머지는 다 포장지(1)임
print(A.shape)
print(A.squeeze().shape) # squeeze() : 인자가 없으면 '모든' 1을 다 없앱니다. (진공 포장)
print(A.squeeze(dim=(0,2,4,5)).shape) # squeeze(dim=...) : 내가 '지정한 위치'의 1만 없앱니다.

B = torch.randn(3,4)
print("======unsqueeze (특정 위치에 1 끼워넣기)======")
print(B.unsqueeze(dim=0).shape) # 맨 앞 추가 -> (1, 3, 4) ★ 제일 많이 씀 (배치 추가)
print(B.unsqueeze(dim=1).shape) # 중간 추가 -> (3, 1, 4)
print(B.unsqueeze(dim=2).shape) # 맨 뒤 추가 -> (3, 4, 1)

print("======reshape (수동으로 모양 잡기)======")
# unsqueeze랑 결과는 똑같음. 단지 모든 숫자를 내가 다 적어야 함.
print(B.reshape(1,3,4).shape) # (1, 3, 4)
print(B.reshape(3,1,4).shape) # (3, 1, 4)
print(B.reshape(3,4,1).shape) # (3, 4, 1)

torch.Size([1, 1, 1, 3, 1, 1, 1, 4, 1, 1, 1])
torch.Size([3, 4])
torch.Size([1, 3, 1, 4, 1, 1, 1])
======unsqueeze (특정 위치에 1 끼워넣기)======
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])
======reshape (수동으로 모양 잡기)======
torch.Size([1, 3, 4])
torch.Size([3, 1, 4])
torch.Size([3, 4, 1])


In [ ]:
A = torch.ones(3,4)
B = torch.zeros(3,4)
C = torch.stack([A,B]) # stack: "새로운 차원을 만들어서 포개기" (두꺼워짐) -> 차원 증가 (+1)
D = torch.cat([A,B], dim=0) # cat (Concatenate): "기존 차원에서 이어 붙이기" (넓어지거나 길어짐) -> 차원 유지
print(C)
print(C.shape)
print(D)
print(D.shape)

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])
torch.Size([6, 4])
